### ISSUE TITLE
npm run train does not work. looks like its missing a discovery_config.json file

### ISSUE THREAD

**Issue by maclean-stu** [chris-anchez/conversation-with-discovery-openwhisk#49]

**Comment by mamoonraja** [comment]
@maclean-stu Thanks a lot for opening the issue. Training files for discovery are in `./manualdocs`. Can you please provide error message?

**Comment by rawslaw** [comment]
I'm hitting the same.  My error message is: 
```Workspace exists
Creating environment
Environment status: active
Creating configuration
fs.js:119
    throw err;
    ^

Error: ENOENT: no such file or directory, open './training/discovery_config.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:348:35)
    at createConfigurationAsync (/renosandbox/hackathon/discovery-assistant-whisk/train-discovery.js:82:23)
    at /renosandbox/hackathon/discovery-assistant-whisk/train-discovery.js:222:7
    at /renosandbox/hackathon/discovery-assistant-whisk/node_modules/async/dist/async.js:4603:26
    at Request._callback (/renosandbox/hackathon/discovery-assistant-whisk/node_modules/watson-developer-cloud/lib/requestwrapper.js:125:9)
    at Request.self.callback (/renosandbox/hackathon/discovery-assistant-whisk/node_modules/watson-developer-cloud/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/renosandbox/hackathon/discovery-assistant-whisk/node_modules/watson-developer-cloud/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:182:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@0.1.0 train: `cp .env.example .env && node ./train-conversation.js && node ./train-discovery.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app@0.1.0 train script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/u070104/.npm/_logs/2018-07-16T18_41_49_477Z-debug.log
```
The contents of that debug log as follows:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/lib/node_modules/node/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'train' ]
2 info using npm@5.0.3
3 info using node@v10.6.0
4 verbose run-script [ 'pretrain', 'train', 'posttrain' ]
5 info lifecycle app@0.1.0~pretrain: app@0.1.0
6 silly lifecycle app@0.1.0~pretrain: no script for pretrain, continuing
7 info lifecycle app@0.1.0~train: app@0.1.0
8 verbose lifecycle app@0.1.0~train: unsafe-perm in lifecycle true
9 verbose lifecycle app@0.1.0~train: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/renosandbox/hackathon/discovery-assistant-whisk/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin
10 verbose lifecycle app@0.1.0~train: CWD: /renosandbox/hackathon/discovery-assistant-whisk
11 silly lifecycle app@0.1.0~train: Args: [ '-c',
11 silly lifecycle   'cp .env.example .env && node ./train-conversation.js && node ./train-discovery.js' ]
12 silly lifecycle app@0.1.0~train: Returned: code: 1  signal: null
13 info lifecycle app@0.1.0~train: Failed to exec train script
14 verbose stack Error: app@0.1.0 train: `cp .env.example .env && node ./train-conversation.js && node ./train-discovery.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at EventEmitter.emit (events.js:182:13)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at ChildProcess.emit (events.js:182:13)
14 verbose stack     at maybeClose (internal/child_process.js:961:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
15 verbose pkgid app@0.1.0
16 verbose cwd /renosandbox/hackathon/discovery-assistant-whisk
17 verbose Darwin 17.5.0
18 verbose argv "/usr/local/lib/node_modules/node/bin/node" "/usr/local/bin/npm" "run" "train"
19 verbose node v10.6.0
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error app@0.1.0 train: `cp .env.example .env && node ./train-conversation.js && node ./train-discovery.js`
23 error Exit status 1
24 error Failed at the app@0.1.0 train script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by mamoonraja** [comment]
I have just debugged the issue, the reason is that default configuration [name](https://github.com/watson-developer-cloud/assistant-with-discovery-openwhisk/blob/master/train-discovery.js#L18) changed to`'Default Configuration'`. I am updating the training script to use the default configuration. Fix coming in soon.
